SEED_RESEARCH_QUESTIONS = [
    {
        "title": "Does AI writing assistance reduce independent argument formation in students?",
        "theme": "education",
        "description": "Study whether AI-generated drafts change how students form claims, evidence, and reasoning.",
        "priority": 5,
    },
    {
        "title": "When does AI summarization improve learning, and when does it reduce deep reading?",
        "theme": "attention",
        "description": "Compare productive summarization support with shallow reading and skipped source inspection.",
        "priority": 5,
    },
    {
        "title": "How does automation bias appear in LLM-assisted decision-making?",
        "theme": "judgment",
        "description": "Track evidence about users over-trusting fluent AI recommendations in decisions.",
        "priority": 5,
    },
    {
        "title": "What product patterns preserve human oversight without creating rubber-stamp approval?",
        "theme": "agency",
        "description": "Find interface patterns that make human review meaningful rather than ceremonial.",
        "priority": 4,
    },
    {
        "title": "How should AI tools protect children from answer dependence while still supporting learning?",
        "theme": "education",
        "description": "Study child-sensitive patterns for scaffolding, reflection, and delayed answers.",
        "priority": 5,
    },
    {
        "title": "Can reflective prompts reduce overreliance on AI recommendations?",
        "theme": "judgment",
        "description": "Evaluate whether asking users to state assumptions or criteria protects independent judgment.",
        "priority": 4,
    },
    {
        "title": "What signs indicate that AI collaboration is causing skill atrophy rather than skill amplification?",
        "theme": "skill",
        "description": "Identify measurable signals that distinguish productive augmentation from capability loss.",
        "priority": 4,
    },
    {
        "title": "How should AI copilots expose uncertainty so users remain actively critical?",
        "theme": "agency",
        "description": "Study uncertainty displays, calibration cues, and source-grounded UI patterns.",
        "priority": 4,
    },
    {
        "title": "What does research say about cognitive offloading and memory formation in digital tools?",
        "theme": "cognitive_offloading",
        "description": "Use cognitive offloading literature as a baseline for AI-native memory and reasoning questions.",
        "priority": 3,
    },
    {
        "title": "Which interface frictions improve learning without making AI tools feel punitive?",
        "theme": "engineering_patterns",
        "description": "Find useful friction patterns that protect cognition while preserving flow.",
        "priority": 4,
    },
]


FIXTURE_SOURCE_DOCUMENTS = [
    {
        "url": "https://www.microsoft.com/en-us/research/publication/the-impact-of-generative-ai-on-critical-thinking-self-reported-reductions-in-cognitive-effort-and-confidence-effects-from-a-survey-of-knowledge-workers/",
        "title": "The Impact of Generative AI on Critical Thinking",
        "authors": "Hao-Ping Lee, Advait Sarkar, Lev Tankelevitch, Ian Drosos, Sean Rintel, Richard Banks, Nicholas Wilson",
        "publisher": "Microsoft Research / CHI 2025",
        "language": "en",
        "source_type": "paper",
        "snippet": "A survey of 319 knowledge workers found that confidence in GenAI is associated with less self-reported critical-thinking effort, while self-confidence is associated with more critical thinking.",
        "credibility_score": 90,
    },
    {
        "url": "https://www.unesco.org/en/articles/guidance-generative-ai-education-and-research",
        "title": "Guidance for Generative AI in Education and Research",
        "authors": "Fengchun Miao, Wayne Holmes",
        "publisher": "UNESCO",
        "language": "en",
        "source_type": "policy",
        "snippet": "UNESCO proposes human-centred, age-appropriate validation and pedagogical design processes for GenAI use in education and research.",
        "credibility_score": 88,
    },
    {
        "url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj?locale=en",
        "title": "Regulation (EU) 2024/1689 Artificial Intelligence Act - Article 14 Human Oversight",
        "authors": "European Parliament and Council of the European Union",
        "publisher": "EUR-Lex",
        "language": "en",
        "source_type": "policy",
        "snippet": "Article 14 requires high-risk AI systems to be designed with human-machine interface tools that allow effective oversight by natural persons.",
        "credibility_score": 94,
    },
    {
        "url": "https://www.science.org/doi/10.1126/science.1207745",
        "title": "Google Effects on Memory: Cognitive Consequences of Having Information at Our Fingertips",
        "authors": "Betsy Sparrow, Jenny Liu, Daniel M. Wegner",
        "publisher": "Science",
        "language": "en",
        "source_type": "paper",
        "snippet": "Four studies suggest people remember less information itself when they expect future access, and remember more about where to access it.",
        "credibility_score": 86,
    },
    {
        "url": "https://www.cac.gov.cn/2026-04/10/c_1777558395078289.htm",
        "title": "人工智能拟人化互动服务管理暂行办法",
        "authors": "中央网络安全和信息化委员会办公室",
        "publisher": "国家互联网信息办公室",
        "language": "zh",
        "source_type": "policy",
        "snippet": "拟人化互动服务应具备过度依赖风险预警、情感边界引导、心理健康保护等安全能力，并为未成年人提供保护模式和使用提醒。",
        "credibility_score": 86,
    },
    {
        "url": "https://www.cse.edu.cn/index/detail.html?category=31&id=4242",
        "title": "中小学生成式人工智能使用指南（2025年版）",
        "authors": "中国教育学会",
        "publisher": "中国教育学会",
        "language": "zh",
        "source_type": "policy",
        "snippet": "指南提出针对不同学段明确生成式人工智能工具使用边界，小学阶段禁止学生独自使用开放式内容生成功能。",
        "credibility_score": 78,
    },
]


FIXTURE_EVIDENCE_CARDS = [
    {
        "source_url": "https://www.microsoft.com/en-us/research/publication/the-impact-of-generative-ai-on-critical-thinking-self-reported-reductions-in-cognitive-effort-and-confidence-effects-from-a-survey-of-knowledge-workers/",
        "claim": "Higher confidence in GenAI is associated with lower critical-thinking effort.",
        "summary": "In a CHI 2025 survey of knowledge workers, confidence in GenAI predicted less self-reported critical-thinking effort, while task-specific self-confidence predicted more critical thinking.",
        "stance": "supports",
        "evidence_strength": 86,
        "relevance_score": 94,
        "risk_domain": "judgment",
        "limitations": "Survey and self-report evidence can reveal associations and lived examples, but it does not prove that GenAI causes durable cognitive decline.",
    },
    {
        "source_url": "https://www.microsoft.com/en-us/research/publication/the-impact-of-generative-ai-on-critical-thinking-self-reported-reductions-in-cognitive-effort-and-confidence-effects-from-a-survey-of-knowledge-workers/",
        "claim": "GenAI changes critical thinking from creation toward verification and stewardship.",
        "summary": "The Microsoft Research paper reports that GenAI-assisted work shifts critical thinking toward checking information, integrating responses, and managing the task rather than only producing original reasoning.",
        "stance": "supports",
        "evidence_strength": 82,
        "relevance_score": 91,
        "risk_domain": "agency",
        "limitations": "The shift can be productive when tools support verification, but harmful if product design hides sources, uncertainty, or the user's initial reasoning step.",
    },
    {
        "source_url": "https://www.unesco.org/en/articles/guidance-generative-ai-education-and-research",
        "claim": "Education-facing GenAI needs age-appropriate, human-centred governance.",
        "summary": "UNESCO frames GenAI in education around human capacity, data privacy, age limits, ethical validation, and pedagogical design rather than unrestricted answer generation.",
        "stance": "weakly_supports",
        "evidence_strength": 78,
        "relevance_score": 90,
        "risk_domain": "education",
        "limitations": "Policy guidance is a strong design input, but it should not be treated as experimental proof that a specific interface improves learning outcomes.",
    },
    {
        "source_url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj?locale=en",
        "claim": "Meaningful human oversight should be designed into the AI interface.",
        "summary": "The EU AI Act's Article 14 treats oversight as a system design requirement for high-risk AI, including human-machine interface tools that allow natural persons to oversee use.",
        "stance": "supports",
        "evidence_strength": 84,
        "relevance_score": 88,
        "risk_domain": "agency",
        "limitations": "The regulation targets legally defined high-risk AI systems; consumer wellness or learning tools may not be in scope, but the design principle transfers well.",
    },
    {
        "source_url": "https://www.science.org/doi/10.1126/science.1207745",
        "claim": "Digital tools can shift memory from content recall toward access-location recall.",
        "summary": "The 2011 Science paper on the Google effect found that expected access to information can reduce recall of the information itself while improving recall of where it can be found.",
        "stance": "supports",
        "evidence_strength": 76,
        "relevance_score": 84,
        "risk_domain": "cognitive_offloading",
        "limitations": "This predates modern LLMs and search-based behavior is not the same as conversational AI delegation, so it should be used as background theory.",
    },
    {
        "source_url": "https://www.cac.gov.cn/2026-04/10/c_1777558395078289.htm",
        "claim": "Anthropomorphic AI services should detect overdependence and preserve exit paths.",
        "summary": "China's interim rules for anthropomorphic AI interaction require risk warnings for overdependence, emotional-boundary guidance, minor protection modes, use-duration reminders, and convenient exit options.",
        "stance": "supports",
        "evidence_strength": 73,
        "relevance_score": 92,
        "risk_domain": "emotional_dependency",
        "limitations": "This is a regulatory source that identifies governance expectations, not empirical evidence that any specific reminder or limit reduces dependency.",
    },
    {
        "source_url": "https://www.cse.edu.cn/index/detail.html?category=31&id=4242",
        "claim": "K-12 GenAI use should vary by developmental stage and avoid unsupervised open-ended generation for younger students.",
        "summary": "The China Education Society guideline recommends boundaries by school stage and says elementary students should not independently use open-ended content-generation functions.",
        "stance": "supports",
        "evidence_strength": 70,
        "relevance_score": 89,
        "risk_domain": "education",
        "limitations": "The guideline is highly relevant to education design in China, but implementation outcomes and classroom effects still need primary research and expert review.",
    },
]


FIXTURE_HYPOTHESES = [
    {
        "title": "Require initial judgment before full AI answers",
        "statement": "For learning and high-stakes reasoning tasks, MindMate should ask users to state an initial judgment or criteria before revealing a complete AI recommendation.",
        "theme": "judgment",
        "evidence_score": 84,
        "product_value_score": 92,
        "engineering_feasibility_score": 84,
        "risk_sensitivity_score": 88,
        "rationale": "Critical-thinking, oversight, and education-governance sources converge on the same product pattern: make the user's reasoning visible before the AI answer becomes the default frame.",
    },
    {
        "title": "Mark child education claims for expert review",
        "statement": "Claims about children, students, and learning outcomes should enter expert review before becoming product copy or strong UX claims.",
        "theme": "education",
        "evidence_score": 78,
        "product_value_score": 86,
        "engineering_feasibility_score": 78,
        "risk_sensitivity_score": 96,
        "rationale": "UNESCO and Chinese education guidance both treat minors as a special-risk context, so MindMate should keep education claims conservative until reviewed by qualified experts.",
    },
]
